DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS login;

CREATE TABLE login (
    loginID   INT			AUTO_INCREMENT PRIMARY KEY,
    user      VARCHAR(25)	NOT NULL UNIQUE,
    pass      VARCHAR(255)	NOT NULL,
    update_at TIMESTAMP    	DEFAULT CURRENT_TIMESTAMP
							ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user (
    userID     INT          PRIMARY KEY,
    email      VARCHAR(254) NOT NULL,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (userID) REFERENCES login(loginID)
);